{% set version = "4.5.5" %}
{% set use_n_python_patch = os.environ.get('OPENCV_USE_N_PYTHON_PATCH', '0') %}
package:
  name: opencv-suite
  version: {{ version }}

source:
  {% if USE_GIT|default(False) %}
  - git_url: https://github.com/opencv/opencv
    git_tag: {{ version }}
    git_depth: 10
{% else %}
  - url: https://github.com/opencv/opencv/archive/{{ version }}.zip
    fn: opencv-{{ version }}.zip
    sha256: fb16b734db3a28e5119d513bd7c61ef417edf3756165dc6259519bb9d23d04e2
{% endif %}
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: fb16b734db3a28e5119d513bd7c61ef417edf3756165dc6259519bb9d23d04e2
    folder: opencv_contrib-{{ version }}

build:
  number: 0
  # Python 2.7 is not supported on Windows
  # Package not supported on s390x
  skip: True  # [(win and py27) or s390x]
  script_env:
    - OPENCV_USE_N_PYTHON_PATCH
  ignore_run_exports:
    - openblas-devel
    - _openmp_mutex # [linux64 or aarch64]

requirements:

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - msinttypes            # [win and py<35]
    - ninja
    - pkg-config
    - {{ cdt('mesa-libGL-devel') }}         # [aarch64]
    - {{ cdt('mesa-libEGL-devel') }}        # [aarch64]
  host:
    - cmake
    - eigen
    - ffmpeg                # [not osx]
    - freetype
    - glib                  # [not ppc64le]
    - gst-plugins-base      # [not ppc64le]
    - gstreamer             # [not ppc64le]
    - harfbuzz              # [not win]
    - hdf5
    - jpeg
    - openjpeg              # [not arm64]
    - openblas-devel        # [x86_64]
    - libpng
    - libprotobuf  ==3.5.1  # [linux64]
    - libtiff
    - libwebp               # [not osx]
    - numpy {{ numpy }}
    - python
    - qt ==5.9.7            # [x86_64 and not ppc64le]
    - qt ==5.15.2           # [arm64 or aarch64]
    - zlib
  run:
    - _openmp_mutex         # [linux64 or aarch64]
    - eigen
    - ffmpeg                # [not osx]
    - freetype
    - glib                  # [not ppc64le]
    - gst-plugins-base      # [not ppc64le]
    - gstreamer             # [not ppc64le]
    - harfbuzz              # [not win]
    - hdf5
    - jpeg
    - openjpeg              # [not arm64]
    - libopenblas           # [x86_64]
    - libpng
    - libprotobuf ==3.5.1   # [linux64]
    - libtiff
    - libwebp               # [not osx]
    - numpy {{ numpy }}
    - python
    - qt ==5.9.7            # [x86_64 and not ppc64le]
    - qt ==5.15.2           # [arm64 or aarch64]
    - zlib

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - python
    - numpy
  files:
    - test-cmake/CMakeLists.txt
    - test-cmake/DisplayImage.cpp
    - test.cpp
  commands:
    - pushd test-cmake
    - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON -G"Visual Studio 14 2015"        # [win32]
    - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON -G"Visual Studio 14 2015 Win64"  # [win64]
    - cmake . -DOpenCV_STATIC=OFF -DOpenCV_SHARED=ON                                  # [not win]
    - cmake --build . --config Release
    - popd
    # Verify dynamic libraries.
    # "bioinspired", Not working in 3.1.0
    {% set opencv_libs = [
         "aruco",
         "bgsegm",
         "calib3d",
         "ccalib",
         "core",
         "datasets",
         "dpm",
         "face",
         "features2d",
         "flann",
         "fuzzy",
         "highgui",
         "imgcodecs",
         "imgproc",
         "line_descriptor",
         "ml",
         "objdetect",
         "optflow",
         "phase_unwrapping",
         "photo",
         "plot",
         "reg",
         "rgbd",
         "saliency",
         "shape",
         "stereo",
         "stitching",
         "structured_light",
         "superres",
         "surface_matching",
         "text",
         "tracking",
         "video",
         "videoio",
         "videostab",
         "xfeatures2d",
         "ximgproc",
         "xobjdetect",
         "xphoto",
    ] %}
    {% for each_opencv_lib in opencv_libs %}
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.dylib                        # [osx]
    - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.so                           # [linux]
    - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}342.dll exit 1  # [win]
    {% endfor %}

about:
  home: http://opencv.org/
  license: BSD 3-clause
  license_family: BSD
  summary: Computer vision and machine learning software library.
  description: |
    OpenCV (Open Source Computer Vision Library) includes several hundreds of computer vision algorithms.
    It has a modular structure,which means that the package includes several shared or static libraries.
  doc_url: http://docs.opencv.org/
  doc_source_url: https://github.com/opencv/opencv/tree/master/doc
